name: gui_component
version: 0.1.0
author: Nicolas Calathus <calathus@gmail.com>
description: generic gui library 
homepage: https://github.com/calathus
environment:
  sdk: '>=0.7.5'
dependencies:
    browser: any
    portable_mirror:
      path: ../portable_mirror
    
    